package com.cqtalk.util.encrypt;

import org.apache.commons.codec.digest.DigestUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

import java.io.FileInputStream;
import java.io.IOException;

@Component
public class MD5Util {

    public static String getFileMD5(String path) {
        String res = null;
        try {
            res = DigestUtils.md5Hex(new FileInputStream(path));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return res;
    }

    public static String getBytesMd5(byte[] bytes) {
        return DigestUtils.md5Hex(bytes);
    }

    // MD5 加密 (每次加密的结果不会变的)
    // 密码+随机的字符串(防止我们的密码被盗)
    public static String md5(String key) {
        if(StringUtils.isBlank(key)) {
            return null;
        }
        return org.springframework.util.DigestUtils.md5DigestAsHex(key.getBytes());
    }

}

/*
    INSERT INTO `file_type` (`suffix`, `name`) VALUES
        ("ace", "Ace压缩档案格式"),
        ("act", "Microsoft office助手文件"),
        ("aif", "音频互交换文件"),
        ("aiff", "音频互交换文件"),
        ("ani", "Win系统动画光标"),
        ("arc", "LH ARC的压缩档案文件"),
        ("arj", "Robert Jung ARJ压缩包文件"),
        ("asd", "Microsoft Word的自动保存文件"),
        ("asf", "Microsoft高级流媒体格式文件"),
        ("asm", "汇编语言源文件"),
        ("asp", "动态网页文件"),
        ("ast", "Astound多媒体文件"),
        ("a3l", "Authorware 3.x库文件"),
        ("a4l", "Authorware 4.x库文件"),
        ("a5l", "Authorware 5.x库文件"),
        ("a3m", "Authorware Macintosh未打包文件"),
        ("a4m", "Authorware Macintosh未打包文件"),
        ("a3w", "未打包的Authorware Windows文件"),
        ("a4w", "未打包的Authorware Windows文件"),
        ("a5w", "未打包的Authorware Windows文件"),
        ("bak", "备份文件"),
        ("bas", "BASIC源文件"),
        ("bat", "批处理文件"),
        ("bin", "二进制文件"),
        ("binhex", "苹果的一种编码格式"),
        ("bmp", "Windows或OS/2位图文件"),
        ("book", "Adobe FrameMaker Book文件"),
        ("box", "Lotus Notes的邮箱文件"),
        ("bpl", "Borlard Delph 4打包库"),
        ("bsp", "Quake图形文件"),
        ("bun", "CakeWalk 声音捆绑文件"),
        ("c0l", "台风波形文件"),
        ("cab", "Microsoft压缩档案文件"),
        ("cad", "Softdek的Drafix CAD文件"),
        ("cam", "Casio照相机格式"),
        ("cap", "压缩音乐文件格式"),
        ("cas", "逗号分开的ASCII文件"),
        ("ccb", "Visual Basic动态按钮配置文件"),
        ("cch", "Corel图表文件"),
        ("cco", "CyberChat数据文件"),
        ("cct", "Macromedia Director Shockwave投影"),
        ("cda", "CD音频轨道"),
        ("cdf", "Microsoft频道定义格式文件"),
        ("cdi", "Philip的高密盘交互格式"),
        ("cdm", "Visual dBASE自定义数据模块文件"),
        ("cdr", "CorelDRAW绘图文件 原始音频CD数据文件"),
        ("cdt", "CorelDRAW模板"),
        ("cdx", "CorelDRAW压缩绘图文件"),
        ("cfg", "配置文件"),
        ("cgi", "公共网关接口脚本文件"),
        ("cgm", "计算机图形元文件"),
        ("ch", "OS/2配置文件"),
        ("chk", "由Windows磁盘碎片整理器或磁盘扫描保存的文件碎片"),
        ("chm", "编译过的HTML文件"),
        ("chp", "Ventura Publisher章节文件"),
        ("chr", "字符集"),
        ("cht", "ChartViem文件"),
        ("cif", "Adaptec CD 创建器 CD映像文件"),
        ("cil", "Clip Gallery下载包"),
        ("cim", "SimCity 2000文件"),
        ("cin", "OS/2改变控制文件用于跟踪INI文件中的变化"),
        ("class", "Java类文件"),
        ("clp", "Java类文件"),
        ("cll", "Crick Software Clicker文件"),
        ("cls", "Visual Basic类文件"),
        ("cmd", "Windows NT，OS/2的命令文件 DOS CD/M命令文件 dBASEⅡ程序文件"),
        ("cpi", "Microsoft MS-DOS代码页信息文件"),
        ("cpl", "控制面板扩展名，Corel颜色板"),
        ("cpp", "C++代码文件"),
        ("cpr", "Corel提供说明书文件"),
        ("cpt", "Corel 照片-绘画图像"),
        ("cst", "Macromedia Director Cast文件"),
        ("cur", "Windows光标文件"),
        ("dbf", "dBASE文件"),
        ("dbx", "DataBearn图像 Microsoft Visual FoxPro表格文件"),
        ("dct", "Microsoft Visual FoxPro数据库容器"),
        ("dcu", "Delphi编译单元文件"),
        ("dcx", "Microsoft Visual FoxPro数据库容器 基于PCX的传真图像宏"),
        ("dir", "MacromediaDirector文件"),
        ("dll", "动态链接库"),
        ("doc", "word文档文件"),
        ("dot", "Microsoft Word文档模板"),
        ("dpl", "Borland Delph 3压缩库"),
        ("drv", "驱动程序"),
        ("drw", "Micrografx Designer/Draw Pro/E绘画文件"),
        ("dsf", "Micrografx Designer/Draw Pro/E绘画文件"),
        ("dsg", "DOOM保存的文件"),
        ("dsm", "Dynamic Studio音乐模块（MOD）文件"),
        ("dsp", "Microsoft Developer Studio工程文件"),
        ("dsq", "Corel QUERY（查询）文件"),
        ("dst", "刺绣机图形文件"),
        ("dsw", "Microsoft Developer Studio工作区文件"),
        ("dta", "World Bank（世界银行）的STARS数据文件"),
        ("dtd", "SGML文档类型定义（DTD）文件"),
        ("dted", "地面高度数字数据（图形的数据格式）文件"),
        ("dtf", "Symantec Q&A相关的数据库数据文件"),
        ("dtm", "DigiTrakker模块文件"),
        ("dun", "Microsoft拔号网络导出文件"),
        ("dv", "数字视频文件（MIME）"),
        ("dwg", "AutoCAD工程图文件 AutoCAD或Generic CADD老版本的绘图格式"),
        ("dxr", "Macromedia Director受保护（不可编辑）电影文件"),
        ("eda", "Ensoniq ASR磁盘映像"),
        ("edd", "元素定义文档（FrameMaker+SGML文档）"),
        ("ede", "Ensoniq EPS磁盘映像"),
        ("edk", "Ensoniq KT磁盘映像"),
        ("edq", "Ensoniq SQ1/SQ2/Ks32磁盘映像"),
        ("eds", "Ensoniq SQ80磁盘映像"),
        ("edv", "Ensoniq VFX-SD磁盘映像"),
        ("efa", "Ensoniq ASR文件"),
        ("efe", "Ensoniq EPS文件"),
        ("efk", "Ensoniq KT文件"),
        ("efq", "Ensoniq SQ1/SQ2/Ks32文件"),
        ("efs", "Ensoniq SQ80文件"),
        ("efv", "Ensoniq VFX-SD文件"),
        ("emd", "ABT扩展模块"),
        ("emf", "Windows增强元文件"),
        ("eml", "Microsoft Outlook Express邮件消息（MIME RTC822）文件"),
        ("exe", "可执行文件或程序"),
        ("fav", "Microsoft Outlook导航条"),
        ("fax", "传真类型图像"),
        ("fcd", "虚拟CD-ROM"),
        ("fdf", "Adobe Acrobat表单文档文件"),
        ("fla", "Adobe Acrobat表单文档文件"),
        ("fnd", "Microsoft Explorer保存的搜索文件（Find applet）"),
        ("fon", "系统字体"),
        ("frt", "Microsoft FoxPro报表文件"),
        ("frx", "Visual Basic表单文本 Microsoft FoxPro报表文件"),
        ("fxp", "经Microsoft FoxPro编译的源文件"),
        ("gdm", "铃声、口哨声和声音板模块格式"),
        ("getright", "GetRight未完成的下载文件"),
        ("gho", "Norton 克隆磁盘映像"),
        ("gid", "Windows 95全局索引文件（包括帮助状态）"),
        ("gif", "CompuServe位图文件"),
        ("gl", "动画格式"),
        ("grp", "程序管理组"),
        ("hex", "Macintosh BinHex2.0文件"),
        ("hlp", "Windows帮助文件"),
        ("hpp", "C++程序头文件"),
        ("hqx", "Macintosh BinHex 4.0文件"),
        ("ht", "HyperTerminal（超级终端）"),
        ("htm", "超文本文档"),
        ("html", "超文本文档"),
        ("htt", "Microsoft超文本模板"),
        ("htx", "扩展HTML模板"),
        ("ico", "Windows图标"),
        ("idx", "Microsoft FoxPro相关数据库索引文件 Symantec Q&A相关数据库索引文件"),
        ("img", "GEM映像"),
        ("inf", "信息文件"),
        ("ini", "初始化文件"),
        ("inp", "Oracle 3.0版或早期版本的表单源代码"),
        ("inrs", "INRS远程通信声频"),
        ("ins", "InstallShield安装脚本 X-Internet签字文件"),
        ("int", "中间代码，当一个源程序经过语法检查后编译产生一个可执行代码"),
        ("iof", "Findit文档"),
        ("iqy", "Microsoft Internet查询文件"),
        ("iso", "根据ISD 9660有关CD-ROM文件系统标准列出CD-ROM上的文件"),
        ("isp", "X-Internet签字文件"),
        ("ist", "数字跟踪设备文件"),
        ("isu", "InstallShield卸装脚本"),
        ("it", "脉冲跟踪系统音乐模块（MOD）文件"),
        ("iti", "脉冲跟踪系统设备"),
        ("its", "脉冲跟踪系统抽样，Internet文档位置"),
        ("iv", "Open Inventor中使用的文件格式"),
        ("ivd", "超过20/20微观数据维数或变量等级文件"),
        ("ivp", "超过20/20的用户子集配置文件"),
        ("ivt", "超过20/20表或集合数据文件"),
        ("ivx", "超过20/20微数据目录文件"),
        ("iw", "Idlewild屏幕保护程序"),
        ("iwc", "Install Watch文档"),
        ("j62", "Ricoh照相机格式"),
        ("jar", "Java档案文件"),
        ("java", "Java源文件"),
        ("jff", "JPEG文件"),
        ("jfif", "JPEG文件"),
        ("jif", "JPEG文件"),
        ("jpe", "JPEG图形文件"),
        ("jpeg", "JPEG图形文件"),
        ("jpg", "JPEG图形文件"),
        ("js", "javascript源文件"),
        ("jsp", "HTML网页的一种"),
        ("kar", "卡拉OK MIDI文件（文本+MIDI）"),
        ("lab", "Visual dBASE标签文件"),
        ("lbt", "Microsoft FoxPro标签文件"),
        ("lbx", "Microsoft FoxPro标签文件"),
        ("ldb", "Microsoft Access加锁文件"),
        ("lha", "LZH更换文件后缀"),
        ("log", "日志文件"),
        ("lzh", "LH ARC压缩档案"),
        ("m1v", "MPEG相关文件（MIME“mpeg”类型）"),
        ("m3d", "Corel Motion 3D动画文件"),
        ("m3u", "MPEG URL（MIME声音文件）"),
        ("mam", "MPEG URL（MIME声音文件）"),
        ("maq", "Microsoft Access查询文件"),
        ("mar", "Microsoft Access报表文件"),
        ("mbx", "Microsoft Outlook保存email格式"),
        ("mcw", "Microsoft Word的Macintosh文档"),
        ("mdb", "Microsoft Access数据库"),
        ("mdn", "Microsoft Access空数据库模板"),
        ("mdw", "Microsoft Access工作组文件"),
        ("mid", "MIDI音乐"),
        ("mmm", "Microsoft多媒体电影"),
        ("mov", "QuickTime for Windows电影"),
        ("mp2", "第二层MPEG音频文件"),
        ("mp3", "第三层MPEG音频文件"),
        ("mp4", "音视频文件"),
        ("mpa", "MPEG相关文件，MIME“mpeg类型”"),
        ("mpe", "MPEG动画文件"),
        ("mpeg", "MPEG动画文件"),
        ("mpg", "MPEG动画文件"),
        ("mpp", "Microsoft工程文件 CAD绘图文件格式"),
        ("mpr", "Microsoft FoxPro菜单（已编译）"),
        ("msi", "Windows 安装器包"),
        ("msn", "Microsoft 网络文档 Descent Mission文件"),
        ("obd", "Microsoft 网络文档 Descent Mission文件"),
        ("obj", "对象文件"),
        ("obz", "Microsoft Office活页夹向导"),
        ("ocx", "Microsoft对象链接与嵌入定制控件"),
        ("ods", "Microsoft Outlook Express邮箱文件"),
        ("oft", "Microsoft Outlook模板"),
        ("opx", "OPL扩展DLL（动态链接库）"),
        ("oss", "Microsoft Office查找文件"),
        ("ost", "Microsoft Exchange / Outlook 离线文件"),
        ("pal", "压缩文件"),
        ("part", "Go！Zilla部分下载文件"),
        ("pas", "Pascal源代码"),
        ("pcs", "PICS动画文件"),
        ("pdf", "便携式文档文件"),
        ("php", "包含有PHP脚本的HTML网页"),
        ("php3", "包含有PHP脚本的HTML网页"),
        ("phtml", "包含有PHP脚本的HTML网页 由Perl分析解释的HTML"),
        ("pm5", "Pagemaker 5.0文件"),
        ("pm6", "Pagemaker 6.0文件"),
        ("pps", "Microsoft Powerpoint幻灯片放映"),
        ("ppt", "Microsoft Powerpoint演示文稿"),
        ("prf", "Windows系统文件，Macromedia导演设置文件"),
        ("psd", "Adobe photoshop位图文件"),
        ("psm", "Protracker Studio模型格式 Epic游戏的源数据文件"),
        ("pst", "Microsoft Outlook个人文件夹文件"),
        ("pwl", "Windows 95口令列表文件"),
        ("qif", "QuickTime相关图像（MIME） Quicken导入文件"),
        ("qt", "QuickTime电影"),
        ("qtm", "QuickTime电影"),
        ("qti", "QuickTime相关图像"),
        ("qtif", "QuickTime相关图像"),
        ("qtp", "QuickTime优先文件"),
        ("qts", "Mac PICT图像文件 QuickTime相关图像"),
        ("qtx", "QuickTime相关图像"),
        ("ra", "RealAudio声音文件"),
        ("ram", "RealAudio元文件"),
        ("rar", "RAR压缩档案（Eugene Roshall格式）"),
        ("rec", "录音机宏 RapidComm声音文件"),
        ("reg", "注册表文件"),
        ("rep", "Visual dBASE报表文件"),
        ("res", "Microsoft Visual C++资源文件"),
        ("rm", "RealAudio视频文件"),
        ("rmf", "Rich Map格式"),
        ("rom", "基于盒式磁带的家庭游戏仿真器文件"),
        ("sav", "游戏保存文件"),
        ("sb", "原始带符号字节（8位）数据"),
        ("sbk", "Creative Labs的Soundfont 1.0 Bank文件 （Soundb laster）/EMU SonndFont v1.x Bank文件"),
        ("sbl", "Shockwave Flash对象文件"),
        ("scf", "Windows Explorer命令文件"),
        ("sch", "Microsoft Schedule+1"),
        ("scp", "拨号网络脚本文件"),
        ("scr", "Windows屏幕保护 传真图像 脚本文件"),
        ("sfx", "RAR自解压档案"),
        ("shtml", "含有服务器端包括（SSI）的HTML文件"),
        ("spl", "Shockwave Flash对象 DigiTrakker抽样"),
        ("sql", "SQL查询语句"),
        ("stm", "shtml的短后缀形式"),
        ("str", "屏幕保护文件"),
        ("swa", "在Macromedia导演文件（MP3文件）中的Shockwave声音文件"),
        ("sys", "系统文件"),
        ("t64", "Commodore 64仿真器磁带映像文件"),
        ("theme", "Windows 95桌面主题文件"),
        ("tif", "标签图像文件格式（TIFF）位图"),
        ("tiff", "标签图像文件格式（TIFF）位图"),
        ("tmp", "Windows临时文件"),
        ("trm", "终端文件"),
        ("txt", "文本文件"),
        ("tz", "老的压缩格式文件"),
        ("vba", "VBase文件"),
        ("vbp", "Microsoft Visual Basic工程文件"),
        ("vbw", "Microsoft Visual Basic工作区文件"),
        ("vbx", "Microsoft Visual Basic用户定制控件"),
        ("vqe", "Yamaha Sound-VQ定位器文件"),
        ("vql", "Yamaha Sound-VQ定位器文件"),
        ("vqf", "Yamaha Sound-VQ文件（可能出现标准）"),
        ("vrf", "Oracle 7配置文件"),
        ("vsl", "下载列表文件（GetRight）"),
        ("wab", "Microsoft Outlook文件"),
        ("wad", "包含有视频、玩家水平和其他信息的DOOM游戏的大文件"),
        ("wal", "Quake 2正文文件"),
        ("wav", "Windows波形声形"),
        ("wbk", "Microsoft Word备份文件"),
        ("wfm", "Visual dBASE Windows表单"),
        ("wfn", "在CorelDRAW中使用的符号"),
        ("wiz", "Microsoft Word向导"),
        ("wrl", "虚拟现实模型"),
        ("wwl", "Microsoft Word内插器文件"),
        ("xlk", "Microsoft Excel备份"),
        ("xll", "Microsoft Excel内插器文件"),
        ("xlm", "Microsoft Excel宏"),
        ("xls", "Microsoft Excel宏"),
        ("xlsx", "Microsoft Excel宏"),
        ("xlt", "Microsoft Excel模板"),
        ("xlv", "Microsoft Excel VBA模块"),
        ("xlw", "Microsoft Excel工作簿/工作区"),
        ("zap", "Microsoft Excel工作簿/工作区"),
        ("zip", "压缩格式文件"),
        ("12m", "Lotus 1-2-3 97 SmartMaster文件"),
        ("123", "Lotus 1-2-3 97文件"),
        ("2d", "VersaCAD的2维绘画文件"),
        ("2gr", "在Windows之下的VGA图形驱动程序/配置文件"),
        ("3gr", "在Windows之下的VGA图形驱动程序/配置文件"),
        ("386", "在386或更高级处理器上使用的文件"),
        ("3d", "VersaCAD的3维绘画文件"),
        ("3dm", "3D NURBS建模器"),
        ("3ds", "3D Studio（DOS下）格式文件"),
        ("4ge", "Informix 4GL编译后代码"),
        ("4gl", "Informix 4GL源代码"),
        ("avi", "视频文件"),
        ("awd", "传真文档"),
        ("com", "网络访问后缀"),
        ("cn", "网络访问后缀"),
        ("org", "网络访问后缀"),
        ("dat", "数据文件"),
        ("dbf", "数据库文件"),
        ("dll", "应用程序拓展"),
        ("gz", "Linux系统压缩包后缀"),
        ("docx", "word文本文档"),
        ("pptx", "幻灯片");
*/
